src/config/rule.ts
src/output.ts

🥅 Catch and log the 'manipulators is empty' error

---

src/output.ts

Adding suggestions on fixing the error

🔊 Fix #5 'Profile name found' error message is not informative

---

.github/workflows/test.yml
package.json

👷 Add test workflow

---

.github/workflows/test.yml
.gitignore
package-lock.json
package.json
vite.config.ts

👷 Add test coverage report

---

.github/workflows/build-publish.yml
.github/workflows/pr-test.yml

👷 Add build-publish workflow

---

src/utils/with-condition.spec.ts
src/utils/with-condition.ts

✨ Add withCondition() utility method

---

src/config/from.test.ts
src/config/from.ts
src/config/manipulator.test.ts
src/config/manipulator.ts
src/karabiner/consumer-key-code.ts

✨ Add mapConsumerKey() and toConsumerKey()

---

src/config/manipulator.test.ts
src/config/manipulator.ts
src/karabiner/karabiner-config.ts

✨ Add toMouseKey()

---

src/output.ts

✨ Add --dry-run support via profile name

---

src/config/from.ts
src/config/manipulator.test.ts
src/config/manipulator.ts
src/config/mouse-motion-to-scroll.test.ts
src/config/mouse-motion-to-scroll.ts
src/karabiner/karabiner-config.ts

✨ Add mouseMotionToScroll()

---

src/output.ts

🐛 Fix --dry-run throws 'Profile not found' error

---

src/config/condition.ts
src/config/double-tap.test.ts
src/config/double-tap.ts
src/config/from.test.ts
src/config/layer.ts
src/config/manipulator.test.ts
src/config/manipulator.ts
src/config/mouse-motion-to-scroll.test.ts
src/config/mouse-motion-to-scroll.ts
src/config/rule.test.ts
src/config/rule.ts
src/index.ts
src/output.ts
src/utils/with-condition.ts

✨ Add mapDoubleTap()

---

src/config/double-tap.test.ts
src/config/double-tap.ts
src/output.ts

✨ Add doubleTapParameters

---

src/config/layer.test.ts
src/config/layer.ts

✨ Allow layer() and simlayer() to have multiple keys

---

src/config/layer.test.ts
src/config/layer.ts

🐛 Fix layer conditions not added to layer toggle manipulators

---

src/config/complex-modifications.test.ts
src/config/complex-modifications.ts
src/config/double-tap.ts
src/config/layer.test.ts
src/config/layer.ts
src/config/manipulator.ts
src/config/mouse-motion-to-scroll.ts
src/config/rule.ts
src/config/simlayer.test.ts
src/config/simlayer.ts
src/index.ts
src/utils/build-context.ts
src/utils/with-modifier.ts

✨ Allow one key to trigger multiple layers

---

src/config/manipulator.ts
src/config/to-type-sequence.test.ts
src/config/to-type-sequence.ts
src/index.ts

✨ Add toTypeSequence() to type a string of keys

---

src/config/double-tap.test.ts
src/config/from.test.ts
src/config/from.ts
src/config/layer.ts
src/config/modifier.test.ts
src/config/modifier.ts
src/config/mouse-motion-to-scroll.test.ts
src/config/mouse-motion-to-scroll.ts
src/config/simlayer.test.ts
src/config/to.test.ts
src/config/to.ts
src/index.ts
src/utils/key-alias.ts
src/utils/multi-modifier.ts
src/utils/optional-modifiers.ts
src/utils/with-mapper.ts

✨ Add side modifier aliases

---

src/config/layer.test.ts
src/config/layer.ts
src/config/simlayer.test.ts
src/config/simlayer.ts

✨ Add layer().modifier()

---

src/index.ts

export RuleBuilder interface for easier use with Deno

export RuleBuilder

---

docs/docs/rules/leader-mode.md
docs/sidebars.js
src/config/layer.test.ts
src/config/layer.ts
src/utils/leader-mode.ts

✨ Add layer().leaderMode()

---

src/config/manipulator.ts
src/config/to.test.ts
src/config/to.ts
src/karabiner/karabiner-config.ts

https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/to/set-variable/

Add support for `set_variable.key_up_value`

---

src/config/layer.test.ts
src/config/layer.ts
src/config/simlayer.test.ts

🐛 Fix hyper layer trigger key not work on other layers

---

src/config/layer.test.ts
src/config/layer.ts

🐛 Fix leader mode on layers

---

src/config/double-tap.test.ts
src/config/double-tap.ts
src/config/duo-layer.ts
src/config/layer.test.ts
src/config/layer.ts
src/config/rule.ts
src/config/support-manipulator.ts

🐛 Fix double tap on layer leader mode

---

src/karabiner/karabiner-config.ts

✨ Add conditions to ToEventOptions

---

src/karabiner/karabiner-config.ts
src/output.ts

✨ Add writeToGlobal() output method

---

src/config/complex-modifications.ts
src/config/condition.ts
src/config/double-tap.ts
src/config/duo-layer.ts
src/config/from.ts
src/config/layer.ts
src/config/manipulator.ts
src/config/modifier.ts
src/config/rule.ts
src/config/simlayer.ts
src/config/simultaneous.ts
src/imports/import-profile.ts
src/output.ts
src/utils/build-context.ts
src/utils/from-modifier-overload.ts
src/utils/key-alias.ts
src/utils/leader-mode.ts
src/utils/optional-modifiers.ts
src/utils/with-condition.ts

Change code style to [prefer == over ===](https://evanliu.dev/programming/coding-style/#-vs)

♻️ Use == instead of ===
